<a href="https://colab.research.google.com/github/Rehman047/Next-Word-Predictor-using-LSTM/blob/main/Next_Word_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nltk

In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
from collections import Counter
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import nltk
from nltk.tokenize import word_tokenize

In [7]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [15]:
document = """
Osamu Dazai is one of the central figures in Bungou Stray Dogs and also one of the most enigmatic.
His story spans two very different lives: one as a cold, brilliant executive in the Port Mafia, and another as an eccentric yet cunning member of the Armed Detective Agency.
Dazai’s life is a constant dance between darkness and light, despair and hope, death and survival.
His journey explores questions of morality, purpose, and human connection.

Early Life and Port Mafia Years
Dazai joined the Port Mafia at an unusually young age.
Though much of his early life remains shrouded in mystery, it is clear that he carried an overwhelming sense of emptiness and nihilism from a very young age.
He displayed suicidal tendencies, often attempting elaborate ways to end his life, but somehow always surviving or losing interest at the last moment.
Ōgai Mori, the ruthless but intelligent boss of the Port Mafia, recognized Dazai’s genius and emotional detachment, seeing in him a potential heir.
Under Mori’s guidance, Dazai rose quickly through the ranks, eventually becoming one of the youngest executives in the mafia’s history.

During these years, Dazai formed a partnership with Chūya Nakahara.
Together, they became known as "Twin Dark," a legendary duo feared across the underworld.
Their personalities clashed constantly: Chūya was hot-headed, passionate, and honorable in his own way, while Dazai was calculating, manipulative, and infuriatingly carefree.
Despite their arguments and sarcastic exchanges, their combined strength made them nearly unstoppable.
One of their most notable missions involved the Arahabaki incident, which tied into Chūya’s mysterious powers and tested their uneasy partnership.

But Dazai’s mafia life was not without meaningful connections.
His most significant bond was with Sakunosuke Oda, known as Odasaku.
Odasaku was different from the rest of the Port Mafia.
He despised unnecessary killing and dreamed of retiring to live quietly as a novelist.
Dazai, who had always seen life as meaningless, was drawn to Odasaku’s humanity and ideals.
Odasaku’s philosophy—that life should be used to protect and save others rather than destroy—deeply influenced Dazai.
This bond ended tragically when Odasaku was killed during a violent conflict with another organization.
In his final moments, he urged Dazai to leave the mafia and dedicate himself to saving people.
This moment became the turning point of Dazai’s life, leading him away from the mafia’s bloodshed.

Joining the Armed Detective Agency
After leaving the Port Mafia, Dazai wandered until he crossed paths with Yukichi Fukuzawa, the leader of the Armed Detective Agency.
Impressed by Dazai’s potential, Fukuzawa welcomed him into the organization.
The ADA’s mission—to use supernatural abilities to protect the people of Yokohama—aligned with Odasaku’s dying wish, giving Dazai a new reason to live, or at least to keep moving forward.

At the ADA, Dazai’s personality revealed itself in unusual ways.
On the surface, he seemed like a clown: constantly making jokes about suicide, flirting with death, or appearing lazy and unmotivated.
But beneath that façade lay one of the sharpest minds in the series.
Dazai became a master strategist, often solving cases not through brute force, but through careful planning, manipulation, and psychological insight.
His ability, "No Longer Human," allows him to nullify any other ability upon touch, making him invaluable in battles against ability users.

Dazai also took on a mentorship role, most notably with Atsushi Nakajima.
Atsushi, an orphan who transforms into a white tiger, initially struggled with self-worth and fear of rejection.
Dazai, in his teasing yet oddly supportive way, guided Atsushi to see his own value and gain confidence.
Their relationship mirrors the one Dazai once shared with Odasaku, suggesting that Dazai saw in Atsushi someone who could be saved from despair the way he himself could not.

Major Conflicts and Arcs
As a member of the ADA, Dazai was constantly drawn back into conflict with his former life.
His knowledge of the Port Mafia’s inner workings gave the ADA an edge in many confrontations, but it also created tension with old acquaintances who questioned his loyalty.

The Guild Arc:
When the American organization known as the Guild, led by Francis Scott Key Fitzgerald, invaded Yokohama, Dazai played a critical role in countering them.
He anticipated moves, manipulated outcomes, and turned desperate situations into victories for the ADA.
While others fought physically, Dazai engaged in a battle of wits and strategy, proving that his mind was his greatest weapon.

The Cannibalism Arc:
Later, a crisis orchestrated by the mysterious Fyodor Dostoevsky forced the Port Mafia and the ADA into an uneasy truce.
The "Cannibalism" plan set the two organizations against one another in a deadly trap.
Dazai, with his uncanny ability to read people, steered the situation carefully, ensuring that the ADA survived and minimizing unnecessary bloodshed.

Dazai vs. Fyodor Dostoevsky:
Fyodor Dostoevsky, a chillingly intelligent man determined to eradicate all ability users, became Dazai’s greatest rival.
Unlike other opponents, Fyodor matched Dazai in cunning and strategy.
Their clashes became battles of intellect and ideology rather than simple physical fights.
Where Dazai manipulates for survival and protection, Fyodor manipulates for destruction.
The rivalry between these two is central to the later arcs of the story.

Decay of the Angel Arc:
Dazai’s most dangerous trial came when he was imprisoned alongside Fyodor in Meursault, a supposedly inescapable prison.
Even here, Dazai maintained control over the situation, setting in motion intricate schemes to ensure his allies’ survival.
While trapped in this deadly chess game with Fyodor, Dazai showcased his brilliance as a strategist, demonstrating that his true battlefield is the mind.

Themes and Character Psychology
At the heart of Dazai’s story lies a constant struggle between death and life.
His endless suicide jokes are not simply humor but reflect his ongoing battle with despair.
He seeks death but simultaneously finds reasons to live, usually through his connections with others.

His contradictions make him fascinating:
- A joker, yet deeply depressed.
- A killer, yet now a savior.
- A manipulator, yet one who desires genuine connection.

His relationships define him:
- Odasaku gave him purpose and direction.
- Chūya remains both rival and comrade, a reminder of his mafia past.
- Atsushi represents hope for the future and redemption.
- Fyodor is his intellectual equal, forcing Dazai to confront his own darkness.

Conclusion
Osamu Dazai’s story in Bungou Stray Dogs is not just about a man switching sides from villain to hero.
It is about a person who has stared into the void of meaninglessness and continues to struggle with it daily.
His past in the Port Mafia, his mentorship in the ADA, his rivalries, and his complex psychology all contribute to making him one of the most compelling characters in the series.
Through Dazai, Bungou Stray Dogs explores profound questions: Can someone truly change?
Is redemption possible?
What gives life meaning in the face of despair?

Above all, Dazai embodies transformation.
From the feared executive who bathed in blood, to the detective who saves lives in his own twisted way, his story remains one of survival, irony, and the search for a reason to keep living.
"""


In [16]:
tokens=word_tokenize(document.lower())

In [17]:
vocab={'UNV':0}
for token in tokens:
  if token in vocab:
    continue
  vocab[token]=len(vocab)


In [18]:
sentences=document.split('\n')

In [20]:
def text_to_indices(text,vocab):
  indices=[]
  for token in word_tokenize(text):
    if token not in vocab:
      token='UNV'
    indices.append(vocab[token])
  return indices

In [21]:
all_tokens=[]
for sentence in sentences:
  all_tokens.append(text_to_indices(sentence.lower(),vocab))

In [25]:
all_tokens[1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 4, 5, 6, 15, 16, 17]

In [26]:
len(all_tokens)

98

In [29]:
train_tokens=[]
for senten in all_tokens:
  for i in range(1,len(senten)):
    train_tokens.append(senten[:i+1])

In [30]:
len(train_tokens)

1305

In [31]:
len_list=[]
for senten in all_tokens:
  len_list.append(len(senten))

In [32]:
final_tokens=[]
for senten in train_tokens:
  final_tokens.append([0]*(max(len_list)-len(senten)) + senten)

In [35]:
len(final_tokens[1000])

40

In [36]:
final_tokens=torch.tensor(final_tokens,dtype=torch.long)

In [37]:
final_tokens.shape

torch.Size([1305, 40])

In [38]:
x=final_tokens[:,:-1]
y=final_tokens[:,-1]

In [39]:
class Data(Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def __len__(self):
    return len(self.x)
  def __getitem__(self,index):
    return self.x[index],self.y[index]

In [42]:
data=Data(x,y)

In [43]:
loader=DataLoader(data,batch_size=32,shuffle=True)

In [44]:
for x,y in loader:
  print(x,y)

tensor([[  0,   0,   0,  ...,  29,   2, 128],
        [  0,   0,   0,  ..., 253,  29,  18],
        [  0,   0,   0,  ..., 372,  29, 373],
        ...,
        [  0,   0,   0,  ...,  29,  10,  11],
        [  0,   0,   0,  ..., 276,  25, 149],
        [  0,   0,   0,  ..., 243, 244,  77]]) tensor([ 27, 526, 374,  32, 324,  44,   2, 200, 496, 192, 103,  29, 471,  29,
         29,  18, 402,   6,  29,  29,  31,  56, 215,   9,  11,  18, 155,  94,
         53,  12, 277, 245])
tensor([[  0,   0,  83,  ...,  27, 263,  91],
        [  0,   0,   0,  ..., 483, 484,  91],
        [  0,   0,   0,  ...,  18, 302,  29],
        ...,
        [  0,   0,   0,  ..., 439,   5,   6],
        [  0,   0,   0,  ...,  29,  87,  88],
        [  0,   0,   0,  ..., 157,  29, 158]]) tensor([265, 198, 137,  42,  27,  43,  41,  29,  49,  27, 226, 338,  51,  29,
          9,  86, 445, 144, 544,  17,   7, 365, 291, 187,   6,  27, 179,   5,
        249, 440,  89,  29])
tensor([[  0,   0,   0,  ...,  21, 407, 313],
    